-- GENERATED from the analytics `appointments` table by development/seed/
-- generate-export-tables.py. The export query does SELECT t.* from it, so the two
-- must match column for column. Do not edit by hand; re-run the generator.

CREATE TABLE appointments (
    patient_appointment_id BIGINT,
    patient_id BIGINT,
    appointment_number STRING,
    start_date_time TIMESTAMP,
    location_id BIGINT,
    end_date_time TIMESTAMP,
    appointment_service_id BIGINT,
    appointment_service_type_id BIGINT,
    status STRING,
    appointment_kind STRING,
    comments STRING,
    related_appointment_id BIGINT,
    creator BIGINT,
    date_created TIMESTAMP,
    changed_by BIGINT,
    date_changed TIMESTAMP,
    voided BOOLEAN,
    voided_by BIGINT,
    date_voided TIMESTAMP,
    void_reason STRING,
    uuid STRING,
    appointment_service_name STRING,
    appointment_service_description STRING,
    appointment_service_voided BOOLEAN,
    appointment_service_uuid STRING,
    appointment_service_color STRING,
    appointment_service_start_time TIMESTAMP,
    appointment_service_end_time TIMESTAMP,
    appointment_service_speciality_id BIGINT,
    appointment_service_max_appointments_limit BIGINT,
    appointment_service_duration_mins BIGINT,
    appointment_service_initial_appointment_status STRING,
    appointment_service_type_name STRING,
    appointment_service_type_duration_mins BIGINT,
    appointment_service_type_voided BOOLEAN,
    appointment_service_type_uuid STRING,
    patient_appointment_provider BIGINT,
    patient_appointment_provider_response STRING
)
