-- GENERATED from the analytics `locations` table by development/seed/
-- generate-export-tables.py. The export query does SELECT t.* from it, so the two
-- must match column for column. Do not edit by hand; re-run the generator.

CREATE TABLE locations (
    location_id BIGINT,
    name STRING,
    description STRING,
    location_tags STRING,
    address1 STRING,
    address2 STRING,
    city_village STRING,
    state_province STRING,
    postal_code STRING,
    country STRING,
    latitude STRING,
    longitude STRING,
    creator BIGINT,
    date_created TIMESTAMP,
    county_district STRING,
    address3 STRING,
    address4 STRING,
    address5 STRING,
    address6 STRING,
    retired BOOLEAN,
    retired_by BIGINT,
    date_retired TIMESTAMP,
    retire_reason STRING,
    parent_location BIGINT,
    uuid STRING,
    changed_by BIGINT,
    date_changed TIMESTAMP,
    address7 STRING,
    address8 STRING,
    address9 STRING,
    address10 STRING,
    address11 STRING,
    address12 STRING,
    address13 STRING,
    address14 STRING,
    address15 STRING
)
