-- GENERATED from the analytics `observations` table by development/seed/
-- generate-export-tables.py. The export query does SELECT t.* from it, so the two
-- must match column for column. Do not edit by hand; re-run the generator.

CREATE TABLE observations (
    obs_id BIGINT,
    obs_voided BOOLEAN,
    location STRING,
    obs_date_time TIMESTAMP,
    question_label STRING,
    question_mapping STRING,
    answer_coded STRING,
    answer_datetime TIMESTAMP,
    answer_drug BIGINT,
    answer_numeric DOUBLE,
    answer_text STRING,
    answer_complex STRING,
    answer_modifier STRING,
    comments STRING,
    date_created TIMESTAMP,
    accession_number STRING,
    encounter_type STRING,
    form_namespace_and_path STRING,
    visit_type STRING,
    visit_date_started TIMESTAMP,
    visit_date_stopped TIMESTAMP,
    obs_void_reason STRING,
    previous_version_obs_id BIGINT,
    parent_obs_id BIGINT,
    answer_coded_uuid STRING,
    creator_uuid STRING,
    encounter_uuid STRING,
    visit_uuid STRING,
    location_uuid STRING,
    obs_uuid STRING,
    obs_group_uuid STRING,
    obs_group_concept_uuid STRING,
    patient_uuid STRING,
    question_uuid STRING
)
