-- GENERATED from the analytics `patients` table by development/seed/
-- generate-export-tables.py. The export query does SELECT t.* from it, so the two
-- must match column for column. Do not edit by hand; re-run the generator.

CREATE TABLE patients (
    patient_id BIGINT,
    given_name STRING,
    middle_name STRING,
    family_name STRING,
    identifiers STRING,
    gender STRING,
    birthdate DATE,
    birthdate_estimated BOOLEAN,
    patient_uuid STRING,
    address_city STRING,
    address_county_district STRING,
    address_state_province STRING,
    address_country STRING,
    address_1 STRING,
    address_2 STRING,
    address_3 STRING,
    address_4 STRING,
    address_5 STRING,
    address_6 STRING,
    address_7 STRING,
    address_8 STRING,
    address_9 STRING,
    address_10 STRING,
    address_11 STRING,
    address_12 STRING,
    address_13 STRING,
    address_14 STRING,
    address_15 STRING,
    address_latitude STRING,
    address_longitude STRING,
    attributes STRING,
    dead BOOLEAN,
    death_date TIMESTAMP,
    cause_of_death INT,
    creator BIGINT,
    date_created TIMESTAMP,
    person_voided BOOLEAN,
    person_void_reason STRING
)
