CREATE TABLE providers (
    provider_id BIGINT NOT NULL,
    person_id BIGINT,
    person_uuid STRING,
    username STRING,
    identifier STRING,
    name STRING,
    given_name STRING,
    middle_name STRING,
    family_name STRING,
    gender STRING,
    birthdate DATE,
    roles STRING,
    retired BOOLEAN,
    retired_by BIGINT,
    date_retired TIMESTAMP(6),
    retire_reason STRING,
    provider_uuid STRING,
    date_created TIMESTAMP(6),
    creator BIGINT,
    changed_by BIGINT,
    date_changed TIMESTAMP(6)
)